%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		Menus 												%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
menu1 = uimenu(figHandle,'Label','File');		
menu1sub1 = uimenu(menu1,'Label','Import Data');
	uimenu(menu1sub1,'Label','Import from BVA','Enable','Off') 
uimenu(menu1,'Label','Load *.mat','Separator','on','Callback',{@loadData});
uimenu(menu1,'Label','Clear from WS','Separator','on','Callback',{@clearData});
uimenu(menu1,'Label','Refresh','Separator','on','Callback',{@refreshData});
uimenu(menu1,'Label','Close GUI','Separator','on','Callback',{@closeFig});


menu2 = uimenu(figHandle,'Label','EEG');
menu2sub1 = uimenu(menu2,'Label','Preprocessing ...');
	uimenu(menu2sub1,'Label','... epochise','Enable','off');
	uimenu(menu2sub1,'Label','... detrend','Enable','off');
	uimenu(menu2sub1,'Label','... baseline alignment','Enable','off');
	uimenu(menu2sub1,'Label','... filtering','Enable','off');
menu2sub2 = uimenu(menu2,'Label','Trial rejection');
	uimenu(menu2sub2,'Label','... by absolute value','Enable','off');
	uimenu(menu2sub2,'Label','... by baseline divergence','Enable','off');
menu2sub3 = uimenu(menu2,'Label','RQA');
	uimenu(menu2sub3,'Label','... Run RQA','Callback',{@runRqa});
	uimenu(menu2sub3,'Label','... Run RQA (ROI)','Callback',{@runRqa,1});
	uimenu(menu2sub3,'Label','... show RP - Set 1','Enable','off');
	uimenu(menu2sub3,'Label','... show RP - Set 1 (ROI) ','Enable','off');
menu2sub4 = uimenu(menu2,'Label','SRA');
	uimenu(menu2sub4,'Label','... Run SRA','Enable','off');

menu3 = uimenu(figHandle,'Label','Plotting');
uimenu(menu3,'Label','raw averages','Callback',{@plotAvg});
uimenu(menu3,'Label','smoohted averages','Callback',{@plotAvg,1});
uimenu(menu3,'Label','difference wave','Callback',{@plotDifference});


menu4 = uimenu(figHandle,'Label','Testing');
uimenu(menu4,'Label','Run permutation test','Callback',{@permtest});

menu5 = uimenu(figHandle,'Label','Help');
uimenu(menu5,'Label','About','Callback',{@aboutDialog});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		Buttons												%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
measureLabels = {'RR','DET','L','Lmax','ENT','LAM','TT','Vmax'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		data source											%%%	
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .9 .4 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','EEG/RQA sets:',...
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on');
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.5 .8 .45 .15],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','listbox',... 
 		'Max',2,'Min',0,... for multiple selection
		'String',wsVars,...
		'Tag','vars',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Callback',{@selectionCallback});
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		Epoch Selection										%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .7 .4 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','Use epochs:',...
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on');
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.7 .7 .1 .06],...
		'Tag','epoch0',...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','edit',... 
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Tooltip','Leave blank to use all epochs in set');
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.82 .685 .01 .06],...
		'BackgroundColor',[.801 .750 .688], ...
		'Style','text',... 
		'String',':',...
		'FontWeight','bold');
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.85 .7 .1 .06],...
		'Tag','epoch1',...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','edit',... 
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Tooltip','Leave blank to use all epochs');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		Channel/ROI selection								%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .6 .4 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','Select channels/ROI:',...		
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on');
uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.5 .5 .45 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','listbox',... 
 		'Max',2,'Min',0,... for multiple selection
		'HorizontalAlignment','left',...
		'Tag','chanList',...
		'Visible','on');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%		Meta Info										%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
buttonTimeScale = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .4 .3 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Timescale:',...
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Callback',{@loadMeta,1});
textTimeScale = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.7 .4 .3 .025],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','unknown',...
		'Tag','timescale',...
		'HorizontalAlignment','center',...
		'Visible','on');
align([buttonTimeScale textTimeScale],'VerticalAlignment','middle');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

buttonLabels = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .35 .3 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Labels:',...
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Callback',{@loadMeta,2});
textLabels = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.7 .35 .3 .025],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','unknown',...
		'Tag','labels',...
		'HorizontalAlignment','center',...
		'Visible','on');
align([buttonLabels textLabels],'distribute','middle');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

buttonPositions = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.05 .3 .3 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Positions:',...
		'FontWeight','bold',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Callback',{@loadMeta,3});
textPositions = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.7 .3 .3 .025],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','text',... 
		'String','unknown',...
		'Tag','position',...
		'HorizontalAlignment','center',...
		'Visible','on');
align([buttonPositions textPositions],'distribute','middle');
		
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%		Status												%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.1 .15 .8 .04],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'FontSize',14,...
		'FontWeight','bold',...
		'String','State: ready',...
		'Tag', 'busytext',...
		'HorizontalAlignment','center');

uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.01 .01 .98 .03],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'FontSize',9,...
		'String',sprintf('(c) Stefan Schinkel 2010-%s',datestr(now,'yy')),...
		'ToolTip','http://people.physik.hu-berlin.de/~schinkel',...
		'HorizontalAlignment','center');

movegui(figHandle,'northwest'); 
set(figHandle,'Visible','on');
%set(figHandle,'HandleVisibility','off');


		
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%		RQA measure selection							%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%uicontrol('Parent',figHandle, ...
%		'Units', 'normalized', ...
%		'Position', [.05 .4 .4 .06],...
%		'BackgroundColor',[.801 .75 .688], ...
%		'Style','text',... 
%		'String','RQA measure:',...
%		'FontWeight','bold',...
%		'HorizontalAlignment','left',...
%		'Visible','on');
%uicontrol('Parent',figHandle, ...
%		'Units', 'normalized', ...
%		'Position', [.7 .4 .25 .06],...
%		'BackgroundColor',[.801 .75 .688], ...
%		'Style','popupmenu',... 
%		'String',measureLabels,...
%		'Tag','measure',...
%		'HorizontalAlignment','right',...
%		'Visible','on');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%		Permutations										%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%		
%uicontrol('Parent',figHandle, ...
%		'Units', 'normalized', ...
%		'Position', [.05 .225 .7 .06],...
%		'BackgroundColor',[.801 .75 .688], ...
%		'Style','text',... 
%		'String','Number of permutations:',...
%		'FontWeight','bold',...
%		'HorizontalAlignment','left');
%uicontrol('Parent',figHandle, ...
%		'Units', 'normalized', ...
%		'Position', [.8 .225 .15 .06],...
%		'BackgroundColor',[0.7020 0.7020 0.7020], ...
%		'Tag','perms',...
%		'String','1500',...
%		'Style','edit',... 
%		'HorizontalAlignment','left');
		
